server:
  port: 8080
  contextPath: /rest
  
robot:
  id:  MARS_RB_01
  coordinate_x_init: 0
  coordinate_y_init: 0
  init_position: NORTH
   
area:
  min_y_coordinate_size: 0
  min_x_coordinate_size: 0
  max_y_coordinate_size: 5
  max_x_coordinate_size: 5

spring:
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: ISO-8859-1     